# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"

before_install:
  - python -m pip install --upgrade pip

install:
  - pip install -r requirements.txt

script:
  - pytest
