# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"

install:
  - "pip install --upgrade pip setuptools wheel"
  - "pip install --only-binary=pandas,numpy numpy pandas"

script:
  - "py.test test_module.py"
